### ISSUE TITLE
TLS1.2 support?

### ISSUE THREAD

**Issue by russ-travix** [rajanadar/VaultSharp#1]
Hi,

Is it possible to get support for TLS1.2 enabled?

You can do this by adding this line somewhere in your initialization code:

System.Net.ServicePointManager.SecurityProtocol = 
SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

Best regards,
Russ.

**Comment by rajanadar** [comment]
hi Russ

thank you very much for using the library.

it is definitely possible to get support for TLS1.2 enabled. but i haven't done that out of the box, in the library, for a few reasons.

because it is a Library, there is no initialization code per se. 
and i wanted to refrain setting global application-affecting properties like

```
System.Net.ServicePointManager.DefaultConnectionLimit
System.Net.ServicePointManager.ServerCertificateValidationCallback
System.Net.ServicePointManager.SecurityProtocol
```

etc.

these settings would affect the whole of the consuming application, and i think a specific library shouldn't do this. it is best left for the startup code of the end application to set these values.

the ideal place to put this code would be your Global.asax.cs or Startup.cs or the right startup code for your application, instead of the library.

does that work for you? please let me know.

- raja

**Comment by rajanadar** [comment]
hey @russ-travix 

let me know if the above suggestion works for you and helps you with your problem.
based on that, i'll close this issue.

thanks,
Raja

**Comment by rajanadar** [comment]
hey @russ-travix 

i'll go ahead and close the issue.
please feel free to reach out to me, if you feel it still doesn't solve your problem.

thanks,
Raja
