### ISSUE TITLE
New fork of VaultSharp

### ISSUE THREAD

**Issue by hoerup** [rajanadar/VaultSharp#118]
A few of us Vaultsharp users got impatient with the lack of progress here, so we have created a fork of VaultSharp to be found here: https://github.com/VaultSharp/VaultSharp/

Please note that we really appreciate the work of @rajanadar and we welcome him to collaborate if he again wants to participate in the vaultsharp community.

Since the VaultSharp package on nuget.org is owned by @rajanadar we could not publish the fork under the old name, so the fork is published under the name "VaultSharp.vNext" : https://www.nuget.org/packages/VaultSharp.vNext/

**Comment by seif** [comment]
:+1:  thanks! @rajanadar Would be good to get access to push to nuget

**Comment by rajanadar** [comment]
thanks @hoerup  and @marusyk

First, I thank you for the support. Second, I apologize for the break. Had a personal medical emergency for a few months. Irrespective of that, I should have added collaborators to this project. I have now added both of you, so that this doesn't happen again EVER.

The plan is as follows.

1. I have already fixed and added several critical open issues, including ones in VaultSharp/VaultSharp
2. In a day, I'll publish 0.11.x version to get that out of the way.
3. I want to spend some time, to figure out how to give you NuGet package permissions as well, if needed.
4. Finally, we can move onto the non-critical issues and progress on it, as a community.

Thanks.

**Comment by Marusyk** [comment]
Hello @rajanadar, glad to hear from you. Hope you are doing well.

What do you think about completely moving it to [VaultSharp ](https://github.com/VaultSharp)organization? You will have Admin permissions there.

**Comment by rajanadar** [comment]
At this point, there is the full history of the project in this repo, along with all issues, right NuGet package names, the documentation website and also closing down on a million download. I am full steam on 1.4.x efforts starting next week. 

I have a lot of other colleagues and projects who work off my fork as well. I would love to not disrupt  them.

I totally understand the concern of another break, and am ready to make you and any number of other folks who were active and passionate, as collaborators to avoid this issue in the future.

**Comment by Marusyk** [comment]
You always can move this project with the full history of the project in this repo, along with all issues to organozation

**Comment by rajanadar** [comment]
@Marusyk, 
Lets talk offline.

**Comment by Marusyk** [comment]
@rajanadar  what do you mean?

**Comment by Marusyk** [comment]
![image](https://user-images.githubusercontent.com/9221694/99573677-0f88c700-29df-11eb-903f-3fdffe5dfb87.png)
@rajanadar what about this?
