### ISSUE TITLE
Hashicorp vault connection with AppRole auth method using role id and secret id throwing exception -{“errors”:[“missing client token”]}

### ISSUE THREAD

**Issue by sudhansu327** [rajanadar/VaultSharp#123]
I have Hashicorp vault V1.1.3 used as backend and the code is throwing exception as "Missing client token" while trying to connect vault through secret id and role id based on AppRole auth method. With further analysis I found it is expecting **namespace** as mandatory property in "**X-Vault-Namespace**" header. Looks like the implementation is already there in 0.11.1002 with the namespace but it is being set as empty since the client is not passing it. I have added an optional parameter for namespace in "VaultClientSettings" parametric constructor and passed the value while initializing this constructor from calling thread. It is working fine now for me after these changes. Not sure others are facing similar issue or this issue is occurring for Vault V1.1.3. 
Dev community of this library - Please take a look into this.

**Comment by mfc19** [comment]
I am using Vault v1.4.1 and VaultSharp 1.4.0.  I still get the missing client token error using App Role Auth.  Below is my code.  What am I missing?

var authMethod = new AppRoleAuthMethodInfo(roleId, secretId);
var vaultClientSettings = new VaultClientSettings(vaultURI, authMethod);
var vaultClient = new VaultClient(vaultClientSettings);

**Comment by rajanadar** [comment]
I'll have a look @mfc19 and respond by tomorrow.

**Comment by mfc19** [comment]
Thanks.  Also does VaultSharp support using Vault Agent?

**Comment by rajanadar** [comment]
@mfc19  i did a test run by generating a role-id and secret-id for 'approle' auth backend and used vaultsharp to login and call a capability. Here is the internal auth login response i get from vault, which shows that Vault was able to authenticate my role-id and secret-id and give me back a token to use for subsequent calls.

```
{
   "request_id":"33ae0f25-8918-8817-8a2c-791d0a61e52b",
   "lease_id":"",
   "renewable":false,
   "lease_duration":0,
   "data":null,
   "wrap_info":null,
   "warnings":null,
   "auth":{
      "client_token":"s.KFDuWgFpRFArjATW2gN6EzsE",
      "accessor":"YdLOV0Q2prhHIe3w5monpzya",
      "policies":[
         "default"
      ],
      "token_policies":[
         "default"
      ],
      "metadata":{
         "role_name":"my-role"
      },
      "lease_duration":1200,
      "renewable":true,
      "entity_id":"ffcf470f-3414-3fa7-cafd-2e572248897e",
      "token_type":"service",
      "orphan":true
   }
}
```

1. Can you please check your app-role mountpoint? Is it the default one or are you using an explicit one? if an explicit one, you need to give it to the AppRoleAuthInfo constructor.
2. Can you please check that the role-id and secret-id are non null and are valid? You can do this using fiddler, or using vault agent or using vaultsharp's beforeapirequestaction delegate on vaultclientsettings?

Let me know.

**Comment by rajanadar** [comment]
> Thanks. Also does VaultSharp support using Vault Agent?

Can you elaborate more on the question? My first thought is that VaultSharp has no relation to Vault agent. But I want to ensure I understand the question fully.

**Comment by mfc19** [comment]
I have vault agent setup locally.  Using the Vault REST API I can just make calls using my local address and don't have to authenticate (vault agent does it).  I don't see a documented way to do this via Vault Sharp.  The vault client is based off of having an authenticated client from a call.

**Comment by rajanadar** [comment]
Vaultsharp works on the same principle as Vault Agbent.

When you use vault agent for local vault (dev mode), it implicitly or explicitly (via env variable etc.)has a vault token which is used for all operations on the vault server. It is somewhat agnostic to you.

Similarly when you use vault sharp to perform a vault operation (say read-role), the vault server needs a vault token for the call to succeed. The way vault sharp provides this vault token is via the role id and secret ID you provided. This is what happens.

1. You initialized Auth info using role if and secret ID. Nothing happens at this time.
2. You initialized vault client using this app role Auth info. Nothing happens at this time. 
3. You make your first functional call e. E.g. Read role or something.

What vault sharp does is, since this is the first functional call and vault sharp hasn't acquired a vault token yet, it internally first makes a call to the app role login url of vault with the role id and secret id to get a vault token. This is a one time operation only. 
Once vault sharp has this vault token, it is then used for this functional call and subsequent calls. 

Does that answer?

**Comment by mfc19** [comment]
yes that makes sense thanks
