### ISSUE TITLE
Drop dependency on newtonsoft and use builtin System.Text.json serializer of .net core 3.1 and above

### ISSUE THREAD

**Issue by KamranShahid** [rajanadar/VaultSharp#163]
is it possible to Drop dependency on newtonsoft and use builtin System.Text.json serializer of .net core 3.1 and above

**Comment by rajanadar** [comment]
@KamranShahid  I have to look into this. Haven't looked at .net core 3.x yet.

**Comment by hoerup** [comment]
2.1 wont be EOL'ed until august 2021 - so imho we need to support the old version with newtonsoft until then

**Comment by rajanadar** [comment]
Got it. Thanks @hoerup  I'll see if there is a way we can create a 3.1 artifact as well for folks who are on that. Let me know if any pointers. Else I'll do some research.

**Comment by KamranShahid** [comment]
> @KamranShahid I have to look into this. Haven't looked at .net core 3.x yet.

3.1 is now quite old dude

**Comment by rajanadar** [comment]
> > @KamranShahid I have to look into this. Haven't looked at .net core 3.x yet.
> 
> 3.1 is now quite old dude

As per this [dotnet core version](https://dotnet.microsoft.com/platform/support/policy/dotnet-core), .NET 3.1 released on Dec 2019. So I wouldn't call it quite old <smile />
But I get your point.

I believe moving forward, VaultSharp can be anchored to .Net Core 2.1, 3.1 and .NET 5 versions. (other core versions are out of support already)

@hoerup  Let me know if you feel otherwise.

**Comment by rajanadar** [comment]
I refreshed my head around the whole .net core vs standard vs .net 5.
Finally, all we need to support is .netstandard 2.0 and .net5.0

However, the dropping of Newtonsoft is a bigger work, since there a lot of Json converters.
Also, I need to change the Json annotations into a preprocessor if/else at ~1200 places.

So, this will take some time.

**Comment by rajanadar** [comment]
A better option would be, sometime in the future, make the library a pure .Net 5 library and then only have System.Text.Json based thing. No #if #else stuff. 

Till then, we may have to live with Newtonsoft.

**Comment by rajanadar** [comment]
hey @KamranShahid 

Newtonsoft is a way bigger work. At least the stepping stone is done.
VaultSharp now supports .Net core 3.x apps and is also on .Net 5 now.

**Comment by rajanadar** [comment]
https://www.nuget.org/packages/VaultSharp/1.4.0.7

**Comment by KamranShahid** [comment]
> hey @KamranShahid
> 
> Newtonsoft is a way bigger work. At least the stepping stone is done.
> VaultSharp now supports .Net core 3.x apps and is also on .Net 5 now.

There is no doubt Newtonsoft was quite old and mature with ltos of features. but since .net core 3.0 peoples are mostly moving to use only built-in System.Text.Json

**Comment by rajanadar** [comment]
Right. And as a consumer of the library, folks can continue to use system text json for their needs. The library doesn't mess with that at all.
