### ISSUE TITLE
AppRole with Response Wrapping

### ISSUE THREAD

**Issue by AnPucel** [rajanadar/VaultSharp#212]
**Describe the feature request or question**
I'm attempting to use VaultSharp for AppRole authentication with response wrapping. It seems like you need to know the `secret_id` before initializing a VaultClient even though it does a lazy login, i.e.:
```
            IAuthMethodInfo authMethod = new AppRoleAuthMethodInfo(roleId, secretId);
            var vaultClientSettings = new VaultClientSettings(vaultAddr, authMethod);
```

I'm curious if there is a pattern to use the unwrap `UnwrapWrappedResponseDataAsync` functionality to unwrap a token for the purposes of using it as a `secret_id` and then AppRole to authenticate after the fact. It seems like right now unwrap requires an already authenticated VaultClient object.

**Link to the Vault API Docs that support this feature**
https://learn.hashicorp.com/tutorials/vault/approle-best-practices

**Additional context**

**Comment by rajanadar** [comment]
hi @AnPucel, let me absorb the question and get back on the weekend.

**Comment by rajanadar** [comment]
hi @AnPucel 

Unwrapping is a 3 step process.

1. Step 1 is for your security team (or vault admins) to generate a secret id for the role, and wrap it. This generates a secret-id, wraps it in a cubbyhole and emits out a wrapping-token which is valid for 60 seconds and for 1 time use.

```

$ vault write -wrap-ttl=60s -force auth/approle/role/jenkins/secret-id 

Key                              Value
---                              -----
wrapping_token:                  s.yzbznr9NlZNzsgEtz3SI56pX

```

2. Step 2: Now, you need to first initialize a VaultSharp vault client, using this cubbyhole wrapping token, so that you can retrieve the secret id, as follows.

```

IAuthMethodInfo wrappedTokenAuthMethod = new TokenAuthMethodInfo(wrappingToken);
var wrappedVaultClientSettings = new VaultClientSettings(vaultAddr, wrappedTokenAuthMethod);

IVaultClient wrappedVaultClient = new VaultClient(wrappedVaultClientSettings);

// because our client is initialized with the wrapping token, we don't and SHOULD NOT
// pass the token in the parameter. Else, it'll deplete its single usage.

Secret<Dictionary<string, object>> secretIdData =  wrappedVaultClient.V1.System
  .UnwrapWrappedResponseDataAsync<Dictionary<string, object>>(null).Result; 


var secretId = secretidData.Data["whatever is the key for secret id"]; // inspect the dictionary to find out. 

```

3. Step 3: Using the retrieved, unwrapped Secret-Id, initialize your actual vaultclient to be used in the rest of the app.

```

// Now create your actual client

IAuthMethodInfo authMethod = new AppRoleAuthMethodInfo(roleId, secretId);
var vaultClientSettings = new VaultClientSettings(vaultAddr, authMethod);

IVaultClient vaultClient = new VaultClient(vaultClientSettings);

// use this vaultClient in the rest of the app

```

Please note that, the time interval between Step 1 and Step 2 is quite tricky, if Step 1 is manual and Step 2 is automated. 
Another option is to automate Step 1 as well, but you would need a privileged token to generate and wrap a secret id in an automated manner. So your app would end up having a privileged token anyways, which can generate secret-ids.

Let me know if you need anything else.

**Comment by AnPucel** [comment]
This is so helpful! I wasn't sure if the right way to go about this was w/ two separate VaultClients with different settings, but this should work great.

**Comment by rajanadar** [comment]
Great to hear. Closing this. Let me know if any issues.
