### ISSUE TITLE
How to get token

### ISSUE THREAD

**Issue by arunprasathv** [rajanadar/VaultSharp#216]
**Describe the bug**

Unable to get token or not sure how to authenticate to our enterprise vault. we use secret mount. 
I'm able to get the secrets using             IAuthMethodInfo authMethod = new AppRoleAuthMethodInfo("rolie-guid", "secret-guid");

I'm passing secret id manually by getting token from the vault(getting secret id by curl using copied token from the vault portal). i want to do it programmatically, but not sure how to do it. 

**VaultSharp Version**
 Latest library.

**Vault Version**
1.7.3

**Comment by rajanadar** [comment]
@arunprasathv

If I understand your question, you want to first use a vault token to retrieve the secret ID. Then use this secret ID for future vault operations.

If the above is correct, then you can do this in 2 steps.

1. Step 1. Initialize a vault client with TokenAuthInfo, which takes a vault token directly. Use this vault client instance to retrieve your secret ID.
2. Step 2. Now initialize your second vault client using the AppRoleAuthInfo with the secret ID retrieved above.

The first vault client instance can be discarded after step 1. The second one is what you would use in the rest of your app life cycle.

Let me know if that answers your question.

**Comment by arunprasathv** [comment]
Hi Raja,

Yes. this is what I wanted to do.  
Step1 - can I do it using the library itself ? does it need any credentials? not sure how to get the token without giving any crednetials. 

Thanks
Arun

**Comment by rajanadar** [comment]
You have hit the chicken and egg problem. To retrieve secrets from vault, you need a token which itself is a secret. The Auth methods help you to achieve it.

Typically, the Auth method credentials are not stored in vault, since you have a recursion problem. It is normally based on ec2 or azure or gcp instances, or certs, or injected by cicd tools etc. You need to do the same for your secret ID. Talk to your security team or cicd team to inject it into the app instance so that when the app starts up, it has access to it in a secure way.

**Comment by rajanadar** [comment]
I am closing this, since this is not a VaultSharp issue. Let me know.
