### ISSUE TITLE
Call back events from Hahsi Corp vault

### ISSUE THREAD

**Issue by VenkateshSrini** [rajanadar/VaultSharp#27]
Hi,
I have a few secrets stored in hashi Corp vault. I'm on cloud foundry platform. I use the secrets stored in Hashi corp vault to make external calls. Now If I invoke the Vault every time before I make a call it degrades the performance. But however it is possible that the secrets change over time and it is possible for me to do a local storage eternally. So if these entries change in Hashi Corp vault will it be possible to make a call back in PCF app. On receiving such an event we can reload the content from Vault. Is that possible.

**Comment by rajanadar** [comment]
thanks @VenkateshSrini for using the library.

Sure, it is definitely possible to have a "timer" mechanism, which when elapsed with refresh the token.
The library cannot do that, since it takes on complex concerns, and takes it away from its key concern, a clean/simple/strongly-typed SDK for the API. Also, timers involve a lot of assumption & threading and complexity about the consumers, which is not a good path.

The easiest option for you would be configure Token with a high TTL (but low enough to make your security team happy) and then have "blind timers" to just refresh the token every TTL-5 minutes or so.

This way, you don't need to fetch it on every call OR write complex timer logic with callbacks etc.

**Comment by jegansivathanu** [comment]
hi
hi,could you please anyone help to use GitHub using vault.i have a requirement that,write and read some secrets using GitHub have already create personal access token in GitHub and i not able to access GitHub repository from .net.thanks in advance
