### ISSUE TITLE
vaultsharp.core.vaultapiexception {"errors":["tls connection required"]}

### ISSUE THREAD

**Issue by tanishagarg-sf** [rajanadar/VaultSharp#322]
**Describe the bug**
A one liner of what the bug is.
vaultsharp.core.vaultapiexception {"errors":["tls connection required"]}

**VaultSharp Version**
The version of VaultSharp package being used
VaultSharp.1.4.0.1
**Vault Version**
The version of Vault server being used

**Does this work with Vault CLI?**
Yes

**Exception Details/Stack Trace/Error Message**
Error message, stack trace you see
System.AggregateException: One or more errors occurred. ---> VaultSharp.Core.VaultApiException: {"errors":["tls connection required"]}

**Any additional info**

.NET version is 4.6.2

**Comment by konidev20** [comment]
Hey @tanishagarg-sf ,

Since your connection is going through a proxy. Have you checked if the connection between the proxy, I reckon the TLS connection is being terminated on the proxy. Ideally, from the proxy there must be another TLS connection to the Vault Server.

It's mainly a configuration issue from your end.
