### ISSUE TITLE
Error: The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by tanishagarg-sf** [rajanadar/VaultSharp#323]
**Describe the bug**
A one liner of what the bug is.
Error: The request was aborted: Could not create SSL/TLS secure channel
**VaultSharp Version**
The version of VaultSharp package being used
VaultSharp.1.4.0.1
**Vault Version**
The version of Vault server being used

**Does this work with Vault CLI?**
Yes

**Comment by konidev20** [comment]
Hey @tanishagarg-sf ,

Since your connection is going through a proxy. Have you checked if the connection between the proxy, I reckon the TLS connection is being terminated on the proxy. Ideally, from the proxy there must be another TLS connection to the Vault Server.

It's mainly a configuration issue from your end.

**Comment by tanishagarg-sf** [comment]
Hi @konidev20 
This is working via curl command, via curl command using proxy i am able to login/read/write secrets. Still you think this can be an issue ?

**Comment by konidev20** [comment]
Have you tested your proxy configuration for the HTTPClient handler?

**Comment by tanishagarg-sf** [comment]
How can i test it ? Same configuration is used by us to talk with other services we use for which we can connection using proxy only.
