### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by MaximBalaganskiy** [rajanadar/VaultSharp#351]
All the recent issues seem to be unattended :(

**Comment by konidev20** [comment]
@MaximBalaganskiy, the project's maintainer, and key contributors have been missing in action for about a year now. I used to contribute actively, but I think Vault's APIs have changed quite a bit; hence the recent issues.

**Comment by rajanadar** [comment]
Work travel has been hectic this year. I'll have a look at the issues this weekend.

**Comment by MaximBalaganskiy** [comment]
I think adding a method to call any api URL will release the pressure. Opening access to polymath would be great

**Comment by Zetanova** [comment]
PR https://github.com/rajanadar/VaultSharp/pull/352 would be already there

**Comment by treyhendon** [comment]
Hey all, just checking in.  I'm trying to get the connection string from the database configuration.  Having access to Polymath would allow me to grab it very easily.

**Comment by rajanadar** [comment]
The APIs didn't change much in the last year, and no real burning issues, and I had unexpected traveling due to 4 bereavements in the family. So its been a bit off.

This year, the apis have some changes, so we will be doing a new release next week, to make it 1.17.5 compatible and all issues addressed.
