### ISSUE TITLE
DataAccessManager is not available to CustomAuthenticationProvider

### ISSUE THREAD

**Issue by srininz77** [rajanadar/VaultSharp#37]
I need **Kubernetes authentication** and it doesn't look like VaultSharp supports it yet. So, I thought of using CustomAuthenticationInfo and pass in a delegate. The problem is the delegate has **no access to HttpDataAccessManager** and I can't create it because it's internal class. Can you make HttpDataAccessManager available to the delegate?

So,
1. the delegate definition should be:
Func<**IDataAccessManager**, `Task<string>>` authenticationTokenAsyncDelegate

2.CustomAuthenticationProvider constructor should have a dependency on HttpDataAccessManager and pass it to the delegate when invoking it.

_Constructor_
public CustomAuthenticationProvider(CustomAuthenticationInfo customAuthenticationInfo, **IDataAccessManager dataAccessManager**, bool continueAsyncTasksOnCapturedContext = false)

_GetTokenAsync_
var token = await _customAuthenticationInfo.AuthenticationTokenAsyncDelegate(**_dataAccessManager**).ConfigureAwait(_continueAsyncTasksOnCapturedContext);

3.AuthenticationProviderFactory should create and pass the DataAccessManager to CustomAuthenticationProvider

return new CustomAuthenticationProvider(customAuthenticationInfo, **new HttpDataAccessManager(baseAddress, serviceTimeout: serviceTimeout, postHttpClientInitializeAction: postHttpClientInitializeAction**), continueAsyncTasksOnCapturedContext);

**Comment by rajanadar** [comment]
@srininz77 thanks for using the library. 
With 0.9.x of VaultSharp, there will be first-class support for Kubernetes. So no need to do this.

But for 0.6.x version, the ```httpdataaccessmanager``` was never intended to be made public. It is an internal helper for the library. And there is nothing special about it. It is a http helper.

You have several options (workarounds) to get the Kubernetes login working: (with 0.6.x)

**Option 1:**

- The whole point of the ```authenticationTokenAsyncDelegate``` is to point it to a method that can return a string token. It has no dependency on httpdataaccessmanager. So you can literally write your own Http-helper method which makes a POST call to your vault kubernetes login URL passing in JWT and role and parsing the response to get a "token". And then the rest of the lib should work in a strong way.
- Of course, the downside to this is that, you have to write that quick http helper, which is pretty much the point of VaultSharp.
- The upside is that, you need to do it just for this login call. The rest of your app can work with the strongly typed VaultSharp library.

**Option 2:**

- The ```httpdataaccessmanager``` has no coupling with the AuthInfo or AuthProvider. 
- What that means is, if you want to grab hold of a ```httpdataaccessmanager``` you can use this temp reflection based hacky-workaround.

```
// note that auth info is optional for unauthenticated endpoints
var unauthenticatedVaultClient = VaultClientFactory.CreateVaultClient(uri, authenticationInfo: null);

// you can now use reflection on the private field of this 'unauthenticatedVaultClient'
// to get the instance of '_dataAccessManager'
// once you have that, you can invoke its MakeRequestAsync to get the response 
// back which will have the token.

// You can discard unauthenticatedVaultClient after this. This was its only purpose.
// Your original VaultClient can be the one with AuthInfo

```
This is a very very temp workaround and hacky at best. Option 1 is a lot better than this, because the code is in your control.

**Option 3:**

- I don't plan to release any updates for 0.6.x at this point.
- But if you are super blocked on this (I wouldn't think so) then let me know the .NET version and your current version of VaultSharp, and I'll see if a beta version can be released with just this fix. Once again, it is not ideal, but will at least be a better option than 2.
- I'll see how it fits into my timeline and weigh if a beta for 0.6.x is worth.

I kind of would recommend Option 1, till 0.9.x comes out by end of month.

There is a high chance that I would just expose a generic MakeHttpRequest method as part of 0.9.x for all such scenarios and provide a helper for the clients, for the future.

Let me know.

**Comment by srininz77** [comment]
Thanks. I will consider option1.
