### ISSUE TITLE
How to avoid exceptions?

### ISSUE THREAD

**Issue by andrewsav-datacom** [rajanadar/VaultSharp#62]
I don't seem to find a way to use this library without it throwing an exception when it things something is wrong. Expired token? Exception. Missing secret? Exception. etc...

http://mattwarren.org/2016/12/20/Why-Exceptions-should-be-Exceptional/
https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions

I want to be able to find out if token is invalid and if path to secret exists, etc without incurring the overhead of the exception throwing and catching. How do I do that?

**Comment by rajanadar** [comment]
Hi @andrewsav-datacom 

Since VaultSharp is a http-api wrapper, it throws an exception, anytime the API does not return http-status-code 2xx. This is a typical behavior.

Without exceptions for error scenarios, the response type of every VaultSharp method will become quite weird. e.g. 
{
 "result": "success/failure",
  "success_data":  "<on_sucess>",
  "failure_reason": "failure_info"
}

etc.

This is still burden on all clients to parse a new model and make sense of it.

A library is written for the happy path w.r.t. its methods' return types. And error paths (hopefully low probability) are covered via Exceptions.

Invalid token, path not existing etc. should be exceptional cases in an application. Hence exceptions.
